/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesCategoryRouteImport } from './routes/categories.$category'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryRoute = CategoriesCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => CategoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/categories/$category': typeof CategoriesCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/categories/$category': typeof CategoriesCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/categories/$category': typeof CategoriesCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/favorites'
    | '/profile'
    | '/settings'
    | '/categories/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/favorites'
    | '/profile'
    | '/settings'
    | '/categories/$category'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/favorites'
    | '/profile'
    | '/settings'
    | '/categories/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$category': {
      id: '/categories/$category'
      path: '/$category'
      fullPath: '/categories/$category'
      preLoaderRoute: typeof CategoriesCategoryRouteImport
      parentRoute: typeof CategoriesRoute
    }
  }
}

interface CategoriesRouteChildren {
  CategoriesCategoryRoute: typeof CategoriesCategoryRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesCategoryRoute: CategoriesCategoryRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
